language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.26"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm Pod::Weaver::Section::Contributors Pod::Elemental::Transformer::List
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
after_success:
  - coverage-report